package:
  name: pycalphad
  version: 0.10.1
source:
  sha256: 8325a327280d971b366da0c6c4bee88ade4b35aa07fccc028381f7c543535e9a
  url: https://files.pythonhosted.org/packages/68/08/f29c25d2e33611464ff819acf13b285a570fdc86ccece237d752e4780db8/pycalphad-0.10.1.tar.gz
build:
  script: ${PYTHON} -m pip install .
requirements:
  build:
    - cross-python_${{ target_platform }}
    - ${{ compiler('cxx') }}
    - python
    - cython
    - numpy
    - scipy
    - pip
  host:
    - python
  run:
    - matplotlib
    - numpy
    - pyparsing
    - pytest
    - scipy
    - python-symengine
    - tinydb
    - xarray
